<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbTrialpermissiongroup', 'doctrine');

/**
 * BaseTbTrialpermissiongroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_trialpermissiongroup
 * @property integer $id_trial
 * @property integer $id_grouppermission
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $id_user
 * @property integer $id_user_update
 * @property TbTrial $TbTrial
 * 
 * @method integer                getIdTrialpermissiongroup()  Returns the current record's "id_trialpermissiongroup" value
 * @method integer                getIdTrial()                 Returns the current record's "id_trial" value
 * @method integer                getIdGrouppermission()       Returns the current record's "id_grouppermission" value
 * @method timestamp              getCreatedAt()               Returns the current record's "created_at" value
 * @method timestamp              getUpdatedAt()               Returns the current record's "updated_at" value
 * @method integer                getIdUser()                  Returns the current record's "id_user" value
 * @method integer                getIdUserUpdate()            Returns the current record's "id_user_update" value
 * @method TbTrial                getTbTrial()                 Returns the current record's "TbTrial" value
 * @method TbTrialpermissiongroup setIdTrialpermissiongroup()  Sets the current record's "id_trialpermissiongroup" value
 * @method TbTrialpermissiongroup setIdTrial()                 Sets the current record's "id_trial" value
 * @method TbTrialpermissiongroup setIdGrouppermission()       Sets the current record's "id_grouppermission" value
 * @method TbTrialpermissiongroup setCreatedAt()               Sets the current record's "created_at" value
 * @method TbTrialpermissiongroup setUpdatedAt()               Sets the current record's "updated_at" value
 * @method TbTrialpermissiongroup setIdUser()                  Sets the current record's "id_user" value
 * @method TbTrialpermissiongroup setIdUserUpdate()            Sets the current record's "id_user_update" value
 * @method TbTrialpermissiongroup setTbTrial()                 Sets the current record's "TbTrial" value
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - herlin25@gmail.com - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbTrialpermissiongroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_trialpermissiongroup');
        $this->hasColumn('id_trialpermissiongroup', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tb_trialpermissiongroup_id_trialpermissiongroup',
             'length' => 8,
             ));
        $this->hasColumn('id_trial', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_grouppermission', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_user_update', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbTrial', array(
             'local' => 'id_trial',
             'foreign' => 'id_trial'));
    }
}