<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbAdministrativedivisiontype', 'doctrine');

/**
 * BaseTbAdministrativedivisiontype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_administrativedivisiontype
 * @property string $dmdvtpnombre
 * @property Doctrine_Collection $TbAdministrativedivision
 * 
 * @method integer                      getIdAdministrativedivisiontype()  Returns the current record's "id_administrativedivisiontype" value
 * @method string                       getDmdvtpnombre()                  Returns the current record's "dmdvtpnombre" value
 * @method Doctrine_Collection          getTbAdministrativedivision()      Returns the current record's "TbAdministrativedivision" collection
 * @method TbAdministrativedivisiontype setIdAdministrativedivisiontype()  Sets the current record's "id_administrativedivisiontype" value
 * @method TbAdministrativedivisiontype setDmdvtpnombre()                  Sets the current record's "dmdvtpnombre" value
 * @method TbAdministrativedivisiontype setTbAdministrativedivision()      Sets the current record's "TbAdministrativedivision" collection
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - herlin25@gmail.com - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbAdministrativedivisiontype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_administrativedivisiontype');
        $this->hasColumn('id_administrativedivisiontype', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tb_administrativedivisiontyp_id_administrativedivisiontyp',
             'length' => 8,
             ));
        $this->hasColumn('dmdvtpnombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbAdministrativedivision', array(
             'local' => 'id_administrativedivisiontype',
             'foreign' => 'id_administrativedivisiontype'));
    }
}