<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbDonor', 'doctrine');

/**
 * BaseTbDonor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_donor
 * @property string $dnrname
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $id_user
 * @property integer $id_user_update
 * @property Doctrine_Collection $TbProject
 * 
 * @method integer             getIdDonor()        Returns the current record's "id_donor" value
 * @method string              getDnrname()        Returns the current record's "dnrname" value
 * @method timestamp           getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()      Returns the current record's "updated_at" value
 * @method integer             getIdUser()         Returns the current record's "id_user" value
 * @method integer             getIdUserUpdate()   Returns the current record's "id_user_update" value
 * @method Doctrine_Collection getTbProject()      Returns the current record's "TbProject" collection
 * @method TbDonor             setIdDonor()        Sets the current record's "id_donor" value
 * @method TbDonor             setDnrname()        Sets the current record's "dnrname" value
 * @method TbDonor             setCreatedAt()      Sets the current record's "created_at" value
 * @method TbDonor             setUpdatedAt()      Sets the current record's "updated_at" value
 * @method TbDonor             setIdUser()         Sets the current record's "id_user" value
 * @method TbDonor             setIdUserUpdate()   Sets the current record's "id_user_update" value
 * @method TbDonor             setTbProject()      Sets the current record's "TbProject" collection
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbDonor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_donor');
        $this->hasColumn('id_donor', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tb_donor_id_donor',
             'length' => 8,
             ));
        $this->hasColumn('dnrname', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_user_update', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbProject', array(
             'local' => 'id_donor',
             'foreign' => 'id_donor'));
    }
}