<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbProjectdocument', 'doctrine');

/**
 * BaseTbProjectdocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_projectdocument
 * @property integer $id_project
 * @property string $prdcfile
 * @property string $prdcdescription
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $id_user
 * @property integer $id_user_update
 * @property TbProject $TbProject
 * 
 * @method integer           getIdProjectdocument()  Returns the current record's "id_projectdocument" value
 * @method integer           getIdProject()          Returns the current record's "id_project" value
 * @method string            getPrdcfile()           Returns the current record's "prdcfile" value
 * @method string            getPrdcdescription()    Returns the current record's "prdcdescription" value
 * @method timestamp         getCreatedAt()          Returns the current record's "created_at" value
 * @method timestamp         getUpdatedAt()          Returns the current record's "updated_at" value
 * @method integer           getIdUser()             Returns the current record's "id_user" value
 * @method integer           getIdUserUpdate()       Returns the current record's "id_user_update" value
 * @method TbProject         getTbProject()          Returns the current record's "TbProject" value
 * @method TbProjectdocument setIdProjectdocument()  Sets the current record's "id_projectdocument" value
 * @method TbProjectdocument setIdProject()          Sets the current record's "id_project" value
 * @method TbProjectdocument setPrdcfile()           Sets the current record's "prdcfile" value
 * @method TbProjectdocument setPrdcdescription()    Sets the current record's "prdcdescription" value
 * @method TbProjectdocument setCreatedAt()          Sets the current record's "created_at" value
 * @method TbProjectdocument setUpdatedAt()          Sets the current record's "updated_at" value
 * @method TbProjectdocument setIdUser()             Sets the current record's "id_user" value
 * @method TbProjectdocument setIdUserUpdate()       Sets the current record's "id_user_update" value
 * @method TbProjectdocument setTbProject()          Sets the current record's "TbProject" value
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - herlin25@gmail.com - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbProjectdocument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_projectdocument');
        $this->hasColumn('id_projectdocument', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tb_projectdocument_id_projectdocument',
             'length' => 8,
             ));
        $this->hasColumn('id_project', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('prdcfile', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('prdcdescription', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_user_update', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbProject', array(
             'local' => 'id_project',
             'foreign' => 'id_project'));
    }
}