<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbModulehelp', 'doctrine');

/**
 * BaseTbModulehelp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_modulehelp
 * @property string $mdhlmodule
 * @property string $mdhltexthelp
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $id_user
 * @property integer $id_user_update
 * 
 * @method integer      getIdModulehelp()   Returns the current record's "id_modulehelp" value
 * @method string       getMdhlmodule()     Returns the current record's "mdhlmodule" value
 * @method string       getMdhltexthelp()   Returns the current record's "mdhltexthelp" value
 * @method timestamp    getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp    getUpdatedAt()      Returns the current record's "updated_at" value
 * @method integer      getIdUser()         Returns the current record's "id_user" value
 * @method integer      getIdUserUpdate()   Returns the current record's "id_user_update" value
 * @method TbModulehelp setIdModulehelp()   Sets the current record's "id_modulehelp" value
 * @method TbModulehelp setMdhlmodule()     Sets the current record's "mdhlmodule" value
 * @method TbModulehelp setMdhltexthelp()   Sets the current record's "mdhltexthelp" value
 * @method TbModulehelp setCreatedAt()      Sets the current record's "created_at" value
 * @method TbModulehelp setUpdatedAt()      Sets the current record's "updated_at" value
 * @method TbModulehelp setIdUser()         Sets the current record's "id_user" value
 * @method TbModulehelp setIdUserUpdate()   Sets the current record's "id_user_update" value
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - herlin25@gmail.com - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbModulehelp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_modulehelp');
        $this->hasColumn('id_modulehelp', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tb_modulehelp_id_modulehelp',
             'length' => 8,
             ));
        $this->hasColumn('mdhlmodule', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('mdhltexthelp', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_user_update', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}