<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbTraitclass', 'doctrine');

/**
 * BaseTbTraitclass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_traitclass
 * @property string $trclname
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $id_user
 * @property integer $id_user_update
 * @property Doctrine_Collection $TbVariablesmeasured
 * 
 * @method integer             getIdTraitclass()        Returns the current record's "id_traitclass" value
 * @method string              getTrclname()            Returns the current record's "trclname" value
 * @method timestamp           getCreatedAt()           Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()           Returns the current record's "updated_at" value
 * @method integer             getIdUser()              Returns the current record's "id_user" value
 * @method integer             getIdUserUpdate()        Returns the current record's "id_user_update" value
 * @method Doctrine_Collection getTbVariablesmeasured() Returns the current record's "TbVariablesmeasured" collection
 * @method TbTraitclass        setIdTraitclass()        Sets the current record's "id_traitclass" value
 * @method TbTraitclass        setTrclname()            Sets the current record's "trclname" value
 * @method TbTraitclass        setCreatedAt()           Sets the current record's "created_at" value
 * @method TbTraitclass        setUpdatedAt()           Sets the current record's "updated_at" value
 * @method TbTraitclass        setIdUser()              Sets the current record's "id_user" value
 * @method TbTraitclass        setIdUserUpdate()        Sets the current record's "id_user_update" value
 * @method TbTraitclass        setTbVariablesmeasured() Sets the current record's "TbVariablesmeasured" collection
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - herlin25@gmail.com - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbTraitclass extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_traitclass');
        $this->hasColumn('id_traitclass', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tb_traitclass_id_traitclass',
             'length' => 8,
             ));
        $this->hasColumn('trclname', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_user_update', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TbVariablesmeasured', array(
             'local' => 'id_traitclass',
             'foreign' => 'id_traitclass'));
    }
}