<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('sfGuardUserDownloads', 'doctrine');

/**
 * BasesfGuardUserDownloads
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_download
 * @property integer $user_id
 * @property integer $id_trial
 * @property integer $id_crop
 * @property string $usdwtype
 * @property string $usdwfile
 * @property timestamp $usdwdate
 * @property float $usdwsize
 * @property TbTrial $TbTrial
 * 
 * @method integer              getIdDownload()  Returns the current record's "id_download" value
 * @method integer              getUserId()      Returns the current record's "user_id" value
 * @method integer              getIdTrial()     Returns the current record's "id_trial" value
 * @method integer              getIdCrop()      Returns the current record's "id_crop" value
 * @method string               getUsdwtype()    Returns the current record's "usdwtype" value
 * @method string               getUsdwfile()    Returns the current record's "usdwfile" value
 * @method timestamp            getUsdwdate()    Returns the current record's "usdwdate" value
 * @method float                getUsdwsize()    Returns the current record's "usdwsize" value
 * @method TbTrial              getTbTrial()     Returns the current record's "TbTrial" value
 * @method sfGuardUserDownloads setIdDownload()  Sets the current record's "id_download" value
 * @method sfGuardUserDownloads setUserId()      Sets the current record's "user_id" value
 * @method sfGuardUserDownloads setIdTrial()     Sets the current record's "id_trial" value
 * @method sfGuardUserDownloads setIdCrop()      Sets the current record's "id_crop" value
 * @method sfGuardUserDownloads setUsdwtype()    Sets the current record's "usdwtype" value
 * @method sfGuardUserDownloads setUsdwfile()    Sets the current record's "usdwfile" value
 * @method sfGuardUserDownloads setUsdwdate()    Sets the current record's "usdwdate" value
 * @method sfGuardUserDownloads setUsdwsize()    Sets the current record's "usdwsize" value
 * @method sfGuardUserDownloads setTbTrial()     Sets the current record's "TbTrial" value
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserDownloads extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_downloads');
        $this->hasColumn('id_download', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'sf_guard_user_downloads_id_download',
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_trial', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_crop', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('usdwtype', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usdwfile', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usdwdate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('usdwsize', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TbTrial', array(
             'local' => 'id_trial',
             'foreign' => 'id_trial'));
    }
}