<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TbFieldhelp', 'doctrine');

/**
 * BaseTbFieldhelp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_fieldhelp
 * @property string $flhlmodule
 * @property string $flhlsession
 * @property string $flhlfield
 * @property string $flhltexthelp
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $id_user
 * @property integer $id_user_update
 * 
 * @method integer     getIdFieldhelp()    Returns the current record's "id_fieldhelp" value
 * @method string      getFlhlmodule()     Returns the current record's "flhlmodule" value
 * @method string      getFlhlsession()    Returns the current record's "flhlsession" value
 * @method string      getFlhlfield()      Returns the current record's "flhlfield" value
 * @method string      getFlhltexthelp()   Returns the current record's "flhltexthelp" value
 * @method timestamp   getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()      Returns the current record's "updated_at" value
 * @method integer     getIdUser()         Returns the current record's "id_user" value
 * @method integer     getIdUserUpdate()   Returns the current record's "id_user_update" value
 * @method TbFieldhelp setIdFieldhelp()    Sets the current record's "id_fieldhelp" value
 * @method TbFieldhelp setFlhlmodule()     Sets the current record's "flhlmodule" value
 * @method TbFieldhelp setFlhlsession()    Sets the current record's "flhlsession" value
 * @method TbFieldhelp setFlhlfield()      Sets the current record's "flhlfield" value
 * @method TbFieldhelp setFlhltexthelp()   Sets the current record's "flhltexthelp" value
 * @method TbFieldhelp setCreatedAt()      Sets the current record's "created_at" value
 * @method TbFieldhelp setUpdatedAt()      Sets the current record's "updated_at" value
 * @method TbFieldhelp setIdUser()         Sets the current record's "id_user" value
 * @method TbFieldhelp setIdUserUpdate()   Sets the current record's "id_user_update" value
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - herlin25@gmail.com - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTbFieldhelp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tb_fieldhelp');
        $this->hasColumn('id_fieldhelp', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tb_fieldhelp_id_fieldhelp',
             'length' => 8,
             ));
        $this->hasColumn('flhlmodule', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('flhlsession', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('flhlfield', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('flhltexthelp', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_user', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_user_update', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}