generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbContactperson
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_contactperson
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        id_contactperson:                      {label: Id}
        cnprfirstname:                         {label: First name}
        cnprmiddlename:                        {label: Middle name}
        cnprlastname:                          {label: Last name}
        id_institution:                        {label: Institution}
        cnpremail:                             {label: Email}
        cnprtelephone:                         {label: Telephone}
        
      list:
        title:          List Contact person
        max_per_page:   10
        display:        [id_contactperson, cnprfirstname, cnprlastname, _institution]
        fields:
          id_contactperson:         {label: Id} 
          cnprfirstname:            {label: First name} 
          cnprlastname:             {label: Last name} 
          _institution:             {label: Institution} 

        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit contact person

      #Configuracion para Nuevo Registro
      new:
        title:          New contact person