# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
    
  metas:
    title:        The Global Agricultural Trial Repository - CGIAR - CCAFS - CIAT
    description:  The Global Agricultural Trial Repository  
    keywords:     Trial, Site, Bibliography, CGIAR, CCAFS, CIAT, Crop, Technology, Variety/Race, Variables measured
    language:     en
    robots:       index, follow

  stylesheets:    [/jquery-ui-1.11.4/jquery-ui.min.css,/bootstrapAdminThemePlugin/css/bootstrap.min.css,/jQueryModalAlert/modal-alerts.css,/datatables/jquery.dataTables.min.css,/autocomplete/autocomplete.css,bootstrap-personalized.css,main.css]
  javascripts:    [jquery-1.11.3.min.js,/jquery-ui-1.11.4/jquery-ui.min.js,/bootstrapAdminThemePlugin/js/bootstrap.min.js,/jQueryModalAlert/modal-alerts.js,/datatables/jquery.dataTables.min.js,/autocomplete/autocomplete.js,functions.js,modulesvalidate.js]


  has_layout:     true
  layout:         layout