generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbTraitclass
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_traitclass
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_traitclass:                    {label: Id} 
          trclname:                         {label: Name} 
        
      list:
        title:          Trait class list
        max_per_page:   10
        display:        [id_traitclass, trclname]
        fields:
          id_traitclass:                    {label: Id} 
          trclname:                         {label: Name} 

        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit trait class

      #Configuracion para Nuevo Registro
      new:
        title:          New trait class