<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    trialsites
 * @subpackage model
 * @author     Herlin R. Espinosa G. - CIAT-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {

    //INICIO FUNCION PARA GRABAR O ACTUALIZAR
    public function save(Doctrine_Connection $conn = null) {
        $EmailAddress = strtolower($this->getEmailAddress());
        $Username = $this->getUsername();
        if (!(preg_match("^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@+([_a-zA-Z0-9-]+\.)*[a-zA-Z0-9-]{2,200}\.[a-zA-Z]{2,6}$", $EmailAddress))) {

            echo "<script> alert('*** Email Address Error! ***'); window.history.back();</script>";
            die();
        }

        //ACTIVACION Y PASSWORD DEL USUARIO
        if ($this->getId() != '') {
            $user_id = $this->getId();
            $Password = $this->getPassword();
            $IsActive = $this->getIsActive();

            if ($Password == '' && $IsActive == 1) {
                $cadena = "[^A-Z0-9]";
                $Password = substr(eregi_replace($cadena, "", md5(rand())) . eregi_replace($cadena, "", md5(rand())) . eregi_replace($cadena, "", md5(rand())), 0, 6);
                $this->setPassword($Password);

                //ENVIO DE NOTIFICACION AL USUARIO SOBRE LA ACTIVACION
                if ($EmailAddress != '') {
                    $sent = date("d-M-Y") . " " . date("h:i:s");
                    $destinatario = trim($EmailAddress);
                    $asunto = "Account Notification";
                    $cuerpo = "<html>";
                    $cuerpo .= "<head>";
                    $cuerpo .= "<title>Account Notification</title>";
                    $cuerpo .= "</head>";
                    $cuerpo .= "<body>";
                    $cuerpo .= "<h1>Account Activated</h1>";
                    $cuerpo .= "<p>";
                    $cuerpo .= "<br><b>Your account is active.</b><br><br>";
                    $cuerpo .= "<b>Username: </b>$Username<br> <b>Password: </b>$Password<br><a href='http://www.agtrials.org/login' target='blank'><b>Sign In</b></a><br><br><b>Please remember to change your password after you login.<br><a href='http://www.agtrials.org/changepassword' target='blank'>Change Password</a></b>";
                    $cuerpo .= "</p>";
                    $cuerpo .= "<br><br><b>Sent:</b> $sent ";
                    $cuerpo .= "</body>";
                    $cuerpo .= "</html>";

                    $SendPHPMailer = SendPHPMailer();
                    $SendPHPMailer->AddAddress($destinatario);
                    $SendPHPMailer->Subject = $asunto;
                    $SendPHPMailer->Body = $cuerpo;
                    $SendPHPMailer->Send();
                }

                //ENVIO DE NOTIFICACION A LOS ADMINISTRADORES DE ACTIVACIONES
                $SFusername = sfContext::getInstance()->getUser()->getUsername();
                $sent = date("d-M-Y") . " " . date("h:i:s");
                $asunto = "Activation New User";
                $cuerpo = "<html>";
                $cuerpo .= "<head>";
                $cuerpo .= "<title>Account Activated</title>";
                $cuerpo .= "</head>";
                $cuerpo .= "<body>";
                $cuerpo .= "<p>";
                $cuerpo .= "<br><b>Account Activated</b><br><br>";
                $cuerpo .= "<b>Activated by: </b>$SFusername<br>";
                $cuerpo .= "<b>Username: </b>$Username<br><br>";
                $cuerpo .= "</p>";
                $cuerpo .= "<br><b>Sent:</b> $sent ";
                $cuerpo .= "</body>";
                $cuerpo .= "</html>";

                $SendPHPMailer = SendPHPMailer();
                $SendPHPMailer->AddAddress("g.hyman@cgiar.org");
                $SendPHPMailer->AddAddress("andrewfarrow72@gmail.com");
                $SendPHPMailer->AddAddress("h.r.espinosa@cgiar.org");
                $SendPHPMailer->Subject = $asunto;
                $SendPHPMailer->Body = $cuerpo;
                $SendPHPMailer->Send();

                //CREACION REGISTRO tb_contactperson
                $C_TbContactperson = Doctrine::getTable('TbContactperson')->findOneByCnpremail(trim($EmailAddress));
                if (count($C_TbContactperson) <= 1) {
                    $SfGuardUserInformation = Doctrine::getTable('SfGuardUserInformation')->findOneByUserId($user_id);
                    $TbContactperson = new TbContactperson();
                    $TbContactperson->setCnprfirstname($this->getFirstName());
                    $TbContactperson->setCnprlastname($this->getLastName());
                    $TbContactperson->setIdInstitution($SfGuardUserInformation->getIdInstitution());
                    $TbContactperson->setCnpremail(trim($EmailAddress));
                    $TbContactperson->setCnprtelephone($SfGuardUserInformation->getTelephone());
                    $TbContactperson->setCreatedAt(date('Y-m-d') . " " . date('H:i:s'));
                    $TbContactperson->setIdUser(1);
                    $TbContactperson->save();
                }
            }
        }
        return parent::save($conn);
    }

}
