generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbInstitution
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_institution
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_institution:                 {label: Id} 
          insname:                        {label: Name} 
          id_country:                     {label: Country}
        
      list:
        title:          Institution list
        max_per_page:   10
        display:        [id_institution, insname, _country]
        fields:
          id_institution:                 {label: Id} 
          insname:                        {label: Name} 
          _country:                       {label: Country}

        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit institution

      #Configuracion para Nuevo Registro
      new:
        title:          New institution