generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbProject
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_project
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        id_project:                                {label: Id} 
        prjname:                                   {label: Name} 
        id_leadofproject:                          {label: Lead of project}
        id_projectimplementinginstitutions:        {label: Project implementing institutions}
        prjprojectimplementingperiodstartdate:     {label: Project implementing period start date}
        prjprojectimplementingperiodenddate:       {label: Project implementing period end date}
        id_donor:                                  {label: Donor}
        prjabstract:                               {label: Abstract}
        prjkeywords:                               {label: Keywords}
        
      list:
        title:           project - Trial group list
        max_per_page:   10
        display:        [id_project,prjname,_leadofproject,_projectimplementinginstitutions,_donor]
        fields:
          id_project:                                {label: Id} 
          prjname:                                   {label: Name} 
          leadofproject:                            {label: Lead of project}
          projectimplementinginstitutions:          {label: Institutions}
          donor:                                    {label: Donor}


        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit project - trial group

      #Configuracion para Nuevo Registro
      new:
        title:          New  project - trial group