generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbRolecontactperson
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_rolecontactperson
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_rolecontactperson:            {label: Id} 
          rcpname:                         {label: Name} 
        
      list:
        title:          Role contact person list
        max_per_page:   10
        display:        [id_rolecontactperson, rcpname]
        fields:
          id_rolecontactperson:             {label: Id} 
          rcpname:                          {label: Name} 

        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit role contact person

      #Configuracion para Nuevo Registro
      new:
        title:          New role contact person