generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbVariety
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_variety
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_variety:                    {label: Id} 
          id_crop:                       {label: Crop} 
          vrtorigin:                     {label: Origin} 
          vrtname:                       {label: Name} 
          vrtsynonymous:                 {label: Synonymous} 
          vrtdescription:                {label: Description} 
        
      list:
        title:          Variety list
        max_per_page:   10
        display:        [id_variety, _crop, vrtorigin, vrtname]
        fields:
          id_variety:                    {label: Id} 
          _crop:                         {label: Crop} 
          vrtorigin:                     {label: Origin} 
          vrtname:                       {label: Name} 


        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit variety

      #Configuracion para Nuevo Registro
      new:
        title:          New variety