<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('sfGuardUserGroup', 'doctrine');

/**
 * BasesfGuardUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $group_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property sfGuardUser $User
 * @property sfGuardGroup $Group
 * 
 * @method integer          getUserId()     Returns the current record's "user_id" value
 * @method integer          getGroupId()    Returns the current record's "group_id" value
 * @method timestamp        getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp        getUpdatedAt()  Returns the current record's "updated_at" value
 * @method sfGuardUser      getUser()       Returns the current record's "User" value
 * @method sfGuardGroup     getGroup()      Returns the current record's "Group" value
 * @method sfGuardUserGroup setUserId()     Sets the current record's "user_id" value
 * @method sfGuardUserGroup setGroupId()    Sets the current record's "group_id" value
 * @method sfGuardUserGroup setCreatedAt()  Sets the current record's "created_at" value
 * @method sfGuardUserGroup setUpdatedAt()  Sets the current record's "updated_at" value
 * @method sfGuardUserGroup setUser()       Sets the current record's "User" value
 * @method sfGuardUserGroup setGroup()      Sets the current record's "Group" value
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_group');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'fixed' => 0,
             'unsigned' => false,
             'length' => 8,
             ));
        $this->hasColumn('group_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'fixed' => 0,
             'unsigned' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}