<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('sfGuardRememberKey', 'doctrine');

/**
 * BasesfGuardRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $remember_key
 * @property string $ip_address
 * @property integer $id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property sfGuardUser $User
 * 
 * @method integer            getUserId()       Returns the current record's "user_id" value
 * @method string             getRememberKey()  Returns the current record's "remember_key" value
 * @method string             getIpAddress()    Returns the current record's "ip_address" value
 * @method integer            getId()           Returns the current record's "id" value
 * @method timestamp          getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()    Returns the current record's "updated_at" value
 * @method sfGuardUser        getUser()         Returns the current record's "User" value
 * @method sfGuardRememberKey setUserId()       Sets the current record's "user_id" value
 * @method sfGuardRememberKey setRememberKey()  Sets the current record's "remember_key" value
 * @method sfGuardRememberKey setIpAddress()    Sets the current record's "ip_address" value
 * @method sfGuardRememberKey setId()           Sets the current record's "id" value
 * @method sfGuardRememberKey setCreatedAt()    Sets the current record's "created_at" value
 * @method sfGuardRememberKey setUpdatedAt()    Sets the current record's "updated_at" value
 * @method sfGuardRememberKey setUser()         Sets the current record's "User" value
 * 
 * @package    AgTrials
 * @subpackage model
 * @author     Herlin R. Espinosa G. - herlin25@gmail.com - CIAT-CCAFS-DAPA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardRememberKey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_remember_key');
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('remember_key', 'string', null, array(
             'type' => 'string',
             'length' => '',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('ip_address', 'string', null, array(
             'type' => 'string',
             'length' => '',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             ));
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'sf_guard_remember_key_id',
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 25,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}