generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbTrial
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_trial
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~ 

      list:
        title:          List Trials
        max_per_page:   10
        display:        [id_trial,_project,_contactperson,_triallocation,trltrialname]
        fields:
          id_trial:               {label: Id}
          _project:               {label: Project}
          _contactperson:         {label: Contact person}
          _triallocation:         {label: Trial location}
          trltrialname:           {label: Name}

        object_actions:
          _edit:      ~
          _show:      ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit trial

      #Configuracion para Nuevo Registro
      new:
        title:          New trial
        
      #Configuracion para la Vista del Registro
      show:  ~
