generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbTriallocation
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_triallocation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_triallocation:             {label: Id} 
          trlcname:                     {label: Name} 
          trlclatitude:                 {label: Latitude} 
          trlclongitude:                {label: Longitude} 
          trlcaltitude:                 {label: Altitude} 
          location:                     {label: Country} 
        
      list:
        title:          Trial location list
        max_per_page:   10
        display:        [id_triallocation, trlcname, trlclatitude, trlclongitude, trlcaltitude]
        fields:
          id_triallocation:             {label: Id} 
          trlcname:                     {label: Name} 
          trlclatitude:                 {label: Latitude} 
          trlclongitude:                {label: Longitude} 
          trlcaltitude:                 {label: Altitude} 
         

        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit Trial location

      #Configuracion para Nuevo Registro
      new:
        title:          New Trial location