generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbDonor
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_donor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_donor:                    {label: Id} 
          dnrname:                     {label: Name} 
        
      list:
        title:          Crop list
        max_per_page:   10
        display:        [id_donor, dnrname]
        fields:
          id_donor:                    {label: Id} 
          dnrname:                     {label: Name} 

        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit donor

      #Configuracion para Nuevo Registro
      new:
        title:          New donor