generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TbExperimentaldesign
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tb_experimentaldesign
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_experimentaldesign:           {label: Id} 
          xpdsname:                        {label: Name} 
        
      list:
        title:          Experimental design list
        max_per_page:   10
        display:        [id_experimentaldesign, xpdsname]
        fields:
          id_experimentaldesign:           {label: Id} 
          xpdsname:                        {label: Name} 

        object_actions:
          _edit:        ~
        batch_actions:  {}
      #Configuracion para Filtro Registros
      filter:  ~

      #Configuracion para Formulario Registro
      form:    ~

      #Configuracion para Edicion Registro
      edit:
        title:          Edit experimental design

      #Configuracion para Nuevo Registro
      new:
        title:          New experimental design